// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbtsdkbqnkwmmsccqeyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBidHNka2Jxbmt3bW1zY2NxZXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODk2NjUsImV4cCI6MjA2NTY2NTY2NX0.u6Y8ttnbAguy0BOjgBvuOPZYI2L-UJxKr1_9RiHK_MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);